pipeline:
  name: delegate
  identifier: delegate
  projectIdentifier: Delegate
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: delegate
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        template:
          templateRef: Delegate
          versionLabel: v.1.0.0
          templateInputs:
            type: CI
            variables:
              - name: TARGET_REPO
                type: String
                value: mansong/delegate
              - name: CONTAINER_CONNECTOR_REF
                type: String
                value: account.Dockerhub
  allowStageExecutions: true
